### ISSUE TITLE
helpfile says plot defaults to TRUE when it defaults to FALSE

### ISSUE THREAD

**Issue by Joe-Hilgard** [RobbievanAert/puniform#1]
?puniform says

plot  
A logical indicating whether a plot showing the relation between observed and expected p-values has to be rendered (default is TRUE)

But the command says:
puniform(mi, ri, ni, sdi, m1i, m2i, n1i, n2i, sd1i, sd2i, tobs, alpha = 0.05,
  side, method, plot = FALSE)

**Comment by RobbievanAert** [comment]
Thank you for notifying me. I fixed the issue by changing the command.

Best,
Robbie
